# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.DateField()),
                ('topic', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=900)),
            ],
        ),
    ]
