# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myidea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
